### ISSUE TITLE
"Tools as dependencies": go vet fails with "import "..." is a program, not an importable package" 

### ISSUE THREAD

**Issue by timbunce** [go-modules-by-example/index#103]
The "Tools as dependencies" example: https://github.com/go-modules-by-example/index/blob/master/010_tools/README.md doesn't address `go vet` failing with `import "..." is a program, not an importable package`.

I can't see a way to disable that specific check in go vet.

I appreciate that go vet is based on heuristics and not perfect, however it is commonly used and developers want to be able to have their work pass go vet cleanly.

See also golang/go#30515

**Comment by myitcv** [comment]
`go vet` will only complain if you run it with the `tools` build tag (or whatever build constraint you use in the `tools.go` file). 

Normally you would not run `go vet -tags tools` as a result, because, by a loose convention, this is the build tag used to identify tools dependencies; `tools.go` will never compile, although it needs to be syntactically correct.

Can you provide more details on how you see `go vet` failing? Do you definitely have a build constraint in your `tools.go`?

**Comment by timbunce** [comment]
My mistake. I think the problem was that I'd put the tool imports into an existing package. Now I've moved them to a separate package it works as expected. Thanks.
